/**
 * Common types of the text2command adapter.
 *
 * The rules are created in the admin tab (see `src-admin`) and stored in `adapter.config.rules`.
 */

/**
 * Translations of one entry. `en`, `de` and `ru` are always available,
 * all other languages are optional and the detection falls back if they are missing.
 */
export interface LanguageMap {
    en: string;
    de: string;
    ru: string;
    [lang: string]: string | undefined;
}

/**
 * Value of one argument of a rule as it is stored by the GUI.
 *
 * `userDeviceControl` may replace an argument at runtime with an already parsed state object,
 * e.g. if the user configured `{"val": 5, "ack": true}`.
 */
export type RuleArgument = string | number | boolean | null | undefined | ioBroker.SettableState;

/**
 * Answer of a rule. Either a text (alternatives separated by `/`) or `true`
 * if the command must only be acknowledged.
 */
export type RuleAck = string | string[] | boolean | null | undefined;

/**
 * Words of a rule. Initially the raw text from the GUI. `findMatched` replaces it in place
 * with the parsed representation (a list of words/alternatives or a regular expression)
 * to not parse the same rule again and again.
 */
export type RuleWords = string | RegExp | (string | string[])[];

/** One rule, as stored in `adapter.config.rules` */
export interface Text2CommandRule {
    /** Unique ID of the rule. Generated by the GUI */
    id?: string;
    /** Name of the rule shown in the GUI */
    name?: string;
    /** Name of the command template, e.g. `whatTimeIsIt`. Key of `commands` in `langModel` */
    template: string;
    /** Words that must be found in the text so this rule matches */
    words?: RuleWords;
    /** Arguments of the rule. The meaning depends on the template */
    args?: RuleArgument[];
    /** Answer of the rule */
    ack?: RuleAck;
    /** If true, the following rules will not be processed if this rule matched */
    _break?: boolean;
}

/** Called with the answer that must be said/written back */
export type AnswerCallback = (response?: string | null) => void;

/** Signature of all command handlers, that could be assigned to a rule template */
export type CommandCallback = (
    lang: ioBroker.Languages,
    text: string,
    args: RuleArgument[] | undefined,
    ack: RuleAck,
    cb: AnswerCallback,
) => void;

/** Called after a state was controlled. `error` is empty if the control was successful */
export type ControlCallback = (error?: string | Error | null) => void;

/** Task that is sent to an external processor (normally a javascript instance) */
export interface ProcessorTask {
    language: ioBroker.Languages;
    command: string;
    withLanguage: boolean;
    from?: string;
    callback?: AnswerCallback;
    [other: string]: unknown;
}

declare global {
    // eslint-disable-next-line @typescript-eslint/no-namespace
    namespace ioBroker {
        interface AdapterConfig {
            /** All configured rules */
            rules: Text2CommandRule[];
            /** ID of the state where the answer must be written to, e.g. `sayit.0.tts.text` */
            sayitInstance: string;
            /** Language of the commands. If empty, the system language is used */
            language: ioBroker.Languages | '';
            /** ID of the state of an external processor, that tries to process the text first */
            processorId: string;
            /** How long to wait for the answer of the external processor */
            processorTimeout: number | string;
            /** Write every single answer into `response` and not only the combined one */
            writeEveryAnswer: boolean;
            /** Do not answer with "I don't understand" if no rule matched */
            noNegativeMessage: boolean;
        }
    }
}
